name: Test
on: [pull_request]
jobs:
  build:
    name: Windows Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.23
      uses: actions/setup-go@v4
      with:
        go-version: '^1.23'
      id: go

    - name: Test
      shell: bash
      if: always()
      run: |
        go test -v ./...
